name: sqlite
version: 0.5.0
description: SQLite bindings for Dart
homepage: https://github.com/pylaligand/dart-sqlite
authors:
  - Sam McCall
  - P.Y. Laligand
  - Razvan Lung
environment:
  sdk: '>=1.8.3 <=2.0.0'
dependencies:
  args: ^1.4.3
  http: ^0.11.3+16
  path: ^1.5.1
  yaml: ^2.1.13
dev_dependencies:
  test: ^0.12.13
